### ISSUE TITLE
Compile a list of Star Trek Ships

### ISSUE THREAD

**Issue by jostut** [g-gonzo/StarTrekvsStarWars#3]
Just be able to show a list for the user

**Comment by g-gonzo** [comment]
I tried to do the same for Star Trek, but again huge differences. But I used the same template as Star Wars to get us up and running.. Also, if we decide to use a different source. That will work as well. I also sourced the information off those two PDF books that I shared. 
Notes: 
Warp speed – Star Trek Star Ships, have a Standard, Cruising, and Max warp speed listed. 
There are no speed at atmosphere or a maneuverability ratings.
Hull – no hull reference so I placed the ships displacement in metric tons. We can do some calculations and generate a hull thickness or generate some kind of hull value.
Shields – we will have to do some research to figure out a way to add a value to Star Trek shields vs Star Wars. 
Torpedoes – Star Trek talks about missiles and then gives a number of launchers.. I just added the number of launchers under the Torpedo category, complete opposite of Star Wars where I guessed how many actual torpedoes are on the ship.
