### ISSUE TITLE
Pull in or build a Star Wars ship library

### ISSUE THREAD

**Issue by jostut** [g-gonzo/StarTrekvsStarWars#7]

**Comment by g-gonzo** [comment]
Okay I started on the StarWarsShips.. I didn’t know what information we really wanted to capture so I probably went a little deeper than I should have..  I used the StarWars Fandom site (Wookiepedia) https://starwars.fandom.com/wiki/Technical_Specifications:_Spacecraft_of_the_Imperium_and_the_Rebel_Alliance  to gather info. I think we are going to run into a problem with speed in general.. Star Wars terminology is based more on light speed.. and Star Trek uses the Warp concept. (warp speed vs light speed) we are going to have to do the math on this…
Also in the Star Wars universe, they have some different ratings for speeds and shields, this may have been taken from the gamming community.. this could be a win in our favor. But here are some notes:
Length – for both SW/ST, standard is (metric system) meters.
Width – same.
Maximum Acceleration – Star Wars has two measurements. 
•	The first is in G - (need to research this?)  Are we talking Gs?
•	The second is in MGLT – Megalight a standard unit of distance in space.
Maximum Atmospheric speed – measured in km/h
Maneuverability – has a DPF rating, not much on that, the higher the number the better.
Shielding – shields have a SBD rating, a common unit of measurement for [deflector shields](https://starwars.fandom.com/wiki/Deflector_shield/Legends). The value indicated how much damage the vessel could withstand before the [hull](https://starwars.fandom.com/wiki/Hull/Legends) started taking damage.
Hull – measured in RU, a unit of measurement for [hull](https://starwars.fandom.com/wiki/Hull/Legends) rating. The value indicated how much damage the vessel could withstand before breaking up.
Cannons – I just went with total count… there are many different kinds, if we really want to get into the weeds, we go deeper… or we can create a method that takes a ships cannon value and adjusts for full armaments. 
Torpedoes – I just went with total of torpedoes on hand (inventory) Example: a ship has 2 launchers, but supplied with 8 torps total..  4 for each tube…
Missiles – I just went with total. 
Tour in space – Star Wars refers to consumables and this dictates how long the ship could last in space, it varies, I went for day as the standard.. Fighters last 1 day, Cruisers last 730 days (2 years)…
